


#ifndef __ERROR_CODES_H__
#define __ERROR_CODES_H__ 


#define ERROR_SOIL_SENSOR_IN_AIR  					(-100)
#define ERROR_SOIL_SENSOR_SHORT_CIRCUITED 			(-101)
#define ERROR_SOIL_SENSOR_IN_WATER					(-102)



#define ERROR_ULTRASONIC_SENSOR_PASSED_MAX_DETECTION   (-200)


#endif /*__ERROR_CODES_H__*/